name: 'Build'

on:
  push:
    branches:
      - dev
    tags:
      - '*'

jobs:
  build-linux:
    runs-on: [self-hosted, FlipperZeroToolchain, Linux, X64]
    steps:
      - name: 'Build linux toolchain'
        run: |
          docker build -t flipperzero-toolchain-linux linux
